### ISSUE TITLE
qhexview/qhexview.cpp:702: pointless test ?

### ISSUE THREAD

**Issue by dcb314** [eteran/qhexview#6]
qhexview/qhexview.cpp:702]: (style) Condition 'x>=line2()' is always true

Source code is

        if(x < line2()) {
            highlighting_ = Highlighting_Data;
        } else if(x >= line2()) {
            highlighting_ = Highlighting_Ascii;
        }

Suggest new code

        if(x < line2()) {
            highlighting_ = Highlighting_Data;
        } else {
            highlighting_ = Highlighting_Ascii;
        }

**Comment by eteran** [comment]
Sure, I suspect that the emitted code will be identical, but slightly cleaner code can never hurt. Thanks!
