### ISSUE TITLE
'Show Comments' in context menu when no comment server

### ISSUE THREAD

**Issue by ArntWork** [eteran/qhexview#9]
The context menu contains a 'Show Comments' entry, even if (like in my case) no comment server is set. I think this is not useful in that case: all other code around comments seems to do "if (showComments_ && commentServer_)", so the context menu item has no effect. 
I think adding an if (commentServer_) around the add_toggle_action_to_menu will do the right thing?

**Comment by eteran** [comment]
Fixed, Thanks!
